# Generated by Django 3.0.5 on 2020-04-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destination_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='img',
            new_name='imgs',
        ),
    ]
