# Generated by Django 3.0.5 on 2020-04-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
    ]
