# Generated by Django 3.0.5 on 2020-04-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20200411_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='imgs',
            new_name='img',
        ),
    ]
